# Generated by Django 5.2.8 on 2025-11-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('TF', 'True/False Question'), ('SA', 'Short Answer Question')], default='MCQ', max_length=3)),
                ('question_text', models.TextField(max_length=300)),
                ('option1', models.CharField(blank=True, max_length=150, null=True)),
                ('option2', models.CharField(blank=True, max_length=150, null=True)),
                ('option3', models.CharField(blank=True, max_length=150, null=True)),
                ('option4', models.CharField(blank=True, max_length=150, null=True)),
                ('correct_option', models.CharField(choices=[('A', 'Option 1'), ('B', 'Option 2'), ('C', 'Option 3'), ('D', 'Option 4')], max_length=1)),
                ('correct_answer_text', models.TextField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.quiz')),
            ],
        ),
    ]
