# Generated by Django 5.2.8 on 2025-11-20 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('duration', models.IntegerField(default=5, help_text='Duration in minutes')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('TF', 'True/False Question'), ('SA', 'Short Answer Question')], default='MCQ', max_length=3)),
                ('question_text', models.TextField(max_length=300)),
                ('option1', models.CharField(blank=True, max_length=150, null=True)),
                ('option2', models.CharField(blank=True, max_length=150, null=True)),
                ('option3', models.CharField(blank=True, max_length=150, null=True)),
                ('option4', models.CharField(blank=True, max_length=150, null=True)),
                ('correct_option', models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1, null=True)),
                ('answer_text_SA', models.TextField(blank=True, null=True)),
                ('answer_text_TF', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.quiz')),
            ],
        ),
    ]
