# Generated by Django 5.2.8 on 2025-11-18 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_quiz_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_option', models.CharField(blank=True, choices=[('A', 'Option 1'), ('B', 'Option 2'), ('C', 'Option 3'), ('D', 'Option 4')], max_length=1, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('question_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_app.question')),
            ],
        ),
    ]
