# Generated by Django 5.2.8 on 2025-11-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_remove_question_correct_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
