# Generated by Django 5.2.8 on 2025-11-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_question_answer_text_question_correct_option_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_text',
            new_name='answer_text_SA',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_text_TF',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
