# Generated by Django 5.2.8 on 2025-11-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_quiz_attempt_student_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='point',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
