# Generated by Django 5.2.8 on 2025-11-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_rename_answer_text_question_answer_text_sa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_text_TF',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], null=True),
        ),
    ]
